wpilibsuite/WPILibInstaller-Avalonia

.github/workflows/gradle-wrapper-validation.yml

A side effect of this PR is that it will enable Actions on this repo and allow more complex PRs like #12 to be tested.

Add Gradle Wrapper Vaidation

---

.github/workflows/ci.yml
WPILibInstaller-Avalonia/ViewModels/StartPageViewModel.cs
WPILibInstaller-Avalonia/WPILibInstaller-Avalonia.csproj
WPILibInstaller.entitlements
azure-pipelines.yml
build.gradle
codesign.sh

https://github.com/prateekma/WPILibInstaller-Avalonia/actions/runs/315934659

Create macOS Installer DMG

---

files/frccode

Fix frccode's path to "code" script for Linux

---

scripts/jdk.gradle

Closes #24
Needs to be tested on Linux and Windows.

Use AdoptOpenJDK 11.0.8 for all platforms

---

files/frcvars.sh

frcvars.sh now sets JAVA_HOME

---

.github/workflows/ci.yml

Reverts wpilibsuite/WPILibInstaller-Avalonia#36

Revert "Remove 3rd-party dependency for certificate import"

---

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs

Add desktop shortcut file for Linux

---

WPILibInstaller-Avalonia/ViewModels/FinalPageViewModel.cs
WPILibInstaller-Avalonia/Views/FinalPage.xaml

Make finish page properly handle vscode settings and popup

---

.github/workflows/ci.yml

This improves the security of those actions

Use the WPILib fork of the notarize and import actions

---

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs

Fix desktop shortcuts not being created on windows

---

WPILibInstaller-Avalonia/Interfaces/IProgramWindow.cs
WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs
WPILibInstaller-Avalonia/Views/MainWindow.xaml.cs

Require selecting folder when downloading all instances of VS Code

---

WPILibInstaller-Avalonia/Models/ShortcutData.cs
WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs

None of the other shortcuts or path changes are added in yet. I'll work on those, but want at least VS Code working.

Fix VS Code desktop shortcut

---

build.gradle

This is more in line with what Linux users will expect.

For Linux tgz, put the files into a directory

---

.github/workflows/ci.yml

Include version number in macOS dmg

---

WPILibInstaller-Avalonia/Interfaces/IProgramWindow.cs
WPILibInstaller-Avalonia/ViewModels/StartPageViewModel.cs
WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs
WPILibInstaller-Avalonia/Views/MainWindow.xaml.cs
WPILibInstaller-Avalonia/Views/VSCodePage.xaml

Fixes #83.
Accompanies wpilibsuite/frc-docs#919.

Clear up VS Code installer page text, add file filter

---

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs

write existing .desktop file to ~/.local/share/applications
Fixes #92

Put icon on launcher for linux

---

WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs
WPILibInstaller-Avalonia/Views/VSCodePage.xaml

Update text to "Download VS Code for Offline Installs"

---

WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs
WPILibInstaller-Avalonia/WPILibInstaller-Avalonia.csproj

Fixes #81.
Updates MessageBox.Avalonia to fix exception
Clarifys error messages

Fix exceptions for dialogs on VS Code page

---

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
WPILibInstaller-Avalonia/Views/InstallPage.xaml

Add a second progress bar for total installation progress

---

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs

Delete mac VS Code zip after install

---

WPILibInstaller-Avalonia/ViewModels/FinalPageViewModel.cs

Add newline so that Mac final text fits

---

WPILibInstaller-Avalonia/ViewModels/StartPageViewModel.cs
WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs
WPILibInstaller-Avalonia/Views/MainWindow.xaml.cs

Fixes #115
macOS doesn't handle the wildcard or tar.gz, switch to gz
Fix resource to always be zip

Fix archive selection

---

WPILibInstaller-Avalonia/ViewModels/StartPageViewModel.cs
WPILibInstaller-Avalonia/Views/StartPage.xaml

Show version on Start Page

---

WPILibInstaller-Avalonia/Models/ShortcutData.cs
WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs
WPILibInstaller-Avalonia/Views/MainWindow.xaml.cs

Use Shell Execute must be used to allow running as admin.
Closes #55

Fix Install as Admin not installing shortcuts

---

WPILibInstaller-Avalonia/Utils/IncorrectPlatformException.cs
WPILibInstaller-Avalonia/ViewModels/StartPageViewModel.cs

This will make sure 32 bit is ran on 32 bit, and 64 bit on 64 bit. Since 32 bit installer will run on 64 bit windows, this is a necessary check.
Closes #70

Verify platform being used for installer.

---

.github/workflows/ci.yml
files/MavenMetaDataFixer.py
files/ScriptBase.py
files/ToolsUpdater.py

* Simplify tools directory manipulation
* Use snake case for variable names
* Use 4-space indent
* Simplify process waiting logic
* Run black autoformatter

Clean up ScriptBase.py, ToolsUpdater.py, and MavenMetaDataFixer.py

---

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs

Create nonexistent leading directories on Linux for .desktop files

---

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs

Set integrated terminal java home and path based on OS

---

.github/workflows/ci.yml

This will let us trigger builds at anytime

Add workflow_dispatch build event

---

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs

Give Linux .desktop file execute permissions

---

WPILibInstaller-Avalonia/Views/MainWindow.xaml

Use consistent back and next button positions

---

gradleriobase/build.gradle

Also fixes missing romi deps
Closes #198

Fix missing roborio JRE from installer

---

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs

Add year to tool shortcut names

---

.github/workflows/ci.yml
IsoCreator/IsoCreator.csproj
WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
WPILibInstaller-Avalonia/ViewModels/MainWindowViewModel.cs
WPILibInstaller-Avalonia/ViewModels/PageViewModelBase.cs
WPILibInstaller-Avalonia/ViewModels/StartPageViewModel.cs
WPILibInstaller-Avalonia/Views/MainWindow.xaml.cs
WPILibInstaller-Avalonia/WPILibInstaller-Avalonia.csproj
build.gradle

Update to .NET 6 and newest version of all dependencies

---

files/ScriptBaseCpp.py

- Fix Python2 compatibility
- Only lowercase script name, not entire path

ScriptBaseCpp fixes

---

WPILibInstaller-Avalonia/App.xaml.cs
WPILibInstaller-Avalonia/Interfaces/IProgramWindow.cs
WPILibInstaller-Avalonia/Models/ShortcutData.cs
WPILibInstaller-Avalonia/Utils/ArchiveUtils.cs
WPILibInstaller-Avalonia/ViewModels/ConfigurationPageViewModel.cs
WPILibInstaller-Avalonia/ViewModels/DeprecatedOsPageViewModel.cs
WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
WPILibInstaller-Avalonia/ViewModels/MainWindowViewModel.cs
WPILibInstaller-Avalonia/ViewModels/StartPageViewModel.cs
WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs
WPILibInstaller-Avalonia/Views/DeprecatedOsPage.xaml
WPILibInstaller-Avalonia/Views/DeprecatedOsPage.xaml.cs
WPILibInstaller-Avalonia/Views/MainWindow.xaml.cs
WPILibInstaller-Avalonia/Views/StartPage.xaml.cs

This window will be the first window shown if using an unsupported windows os.

Add page for deprectated operating systems

---

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs

Previously, if the prompt was missed or cancelled the whole install would have to be retried.
Closes #212 
Closes #137

Allow retry on shortcut creator if UAC prompt is cancelled or missed

---

scripts/jdk.gradle

Fix JDK version replacement

---

files/MavenMetaDataFixer.py
files/ScriptBase.py
files/ScriptBaseCpp.py
files/ToolsUpdater.py

Fixes #203 (macOS)
Fixes installation on Ubuntu 20.04

Explicitly use python3

---

apps/ToolsUpdater/build.gradle
build.gradle
gradleriobase/build.gradle

gson was removed from gradleriobase because it's unused.

Upgrade installer dependencies except for shadow

---

files/ScriptBaseCpp.py

Fix executable case in ScriptBaseCpp.py

---

gradleriobase/build.gradle

Also makes the build error error if there is ever a transitive update

Upgrade junit to 4.13.1

---

build.gradle

This reverts commit a806130968f8794142d17ce4cab05ebcdb56f9f7.

Fix exe missing from installer

---

WPILibInstaller-Avalonia/Utils/HttpClientDownloadWithProgress.cs
WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs

We never used cancellation tokens anyway, so just remove them, which removes the only existing failure case we were checking for.
Closes #263

Fix new nullable warnings in newer .NET 6 versions

---

scripts/toolchain.gradle

M1 version will be done in the M1 PR

Update to 2023 toolchains

---

WPILibInstaller-Avalonia/Models/VSCodeModel.cs
WPILibInstaller-Avalonia/Models/VsCodeConfig.cs
WPILibInstaller-Avalonia/ViewModels/StartPageViewModel.cs
WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs
scripts/versions.gradle
scripts/vscode.gradle

Verify VS Code hash of zips and downloads

---

WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs

Reverts wpilibsuite/WPILibInstaller-Avalonia#273
I forgot we used universal.

Revert "Add mac arm vscode to all platform vscode download"

---

WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs
WPILibInstaller-Avalonia/Views/VSCodePage.xaml

We only have 3 items, so we only need 3 bars.

Remove extra progress bar

---

WPILibInstaller-Avalonia/WPILibInstaller-Avalonia.csproj

Update avalonia to newer version

---

.github/workflows/ci.yml
WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
WPILibInstaller-Avalonia/WPILibInstaller-Avalonia.csproj

Update to .NET 7, switch to new file permission API

---

scripts/maven.gradle

Fix arm artifacts not being used for M1 build

---

WPILibInstaller-Avalonia/WPILibInstaller-Avalonia.csproj

New avalonia has a bug that causes it to not work in certain cases

Use old avalonia on linux

---

apps/ToolsUpdater/src/main/java/Program.java

Fix platform path to properly extract on new platforms

---

.github/workflows/ci.yml

This reverts commit fe70dd8927b2332d74a608f27595c6ac6d937f57.

Revert "Disable Mac notarization (#270)"

---

WPILibInstaller-Avalonia/ViewModels/FinalPageViewModel.cs
WPILibInstaller-Avalonia/Views/FinalPage.xaml

Add known issues and changelog buttons

---

build.gradle
gradle.properties
scripts/maven.gradle
scripts/versions.gradle

This will build, but won't be correct until it picks up an updated native utils

Switch macOS to use universal binaries, update to beta 4

---

apps/ToolsUpdater/src/main/java/Program.java

Fix extraction classifier for osx universal

---

scripts/versions.gradle

Also update cpptools to 1.13.8

Update vscode to 1.74.2

---

WPILibInstaller-Avalonia/Utils/IncorrectPlatformException.cs
WPILibInstaller-Avalonia/ViewModels/MainWindowViewModel.cs
WPILibInstaller-Avalonia/ViewModels/StartPageViewModel.cs
WPILibInstaller-Avalonia/Views/MainWindow.xaml.cs

Fix view model initialization order to fix error page

---

WPILibInstaller-Avalonia/ViewModels/StartPageViewModel.cs

Change resources error message from unmount to eject

---

scripts/jdk.gradle

Include src.zip files

---

scripts/versions.gradle

Fixes a bug with the wpilib icon

Update to VS Code 1.83.1

---

WPILibInstaller-Avalonia/Interfaces/IConfigurationProvider.cs
WPILibInstaller-Avalonia/Models/AdvantageScopeConfig.cs
WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
WPILibInstaller-Avalonia/ViewModels/StartPageViewModel.cs
build.gradle
scripts/advantagescope.gradle
scripts/versions.gradle

Install AdvantageScope

---

gradleriobase/build.gradle

include XRP and Romi dependencies

---

gradleriobase/build.gradle

See https://github.com/wpilibsuite/allwpilib/pull/5909 for more details.

Declare platform launcher dependency explicitly

---

WPILibInstaller-Avalonia/Models/ShortcutData.cs
WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
WPILibShortcutCreator/ShortcutData.json
WPILibShortcutCreator/src/main/cpp/ShortcutCreator.cpp
WPILibShortcutCreator/src/main/cpp/ShortcutData.cpp
WPILibShortcutCreator/src/main/cpp/main.cpp
WPILibShortcutCreator/src/main/headers/ShortcutCreator.h
WPILibShortcutCreator/src/main/headers/ShortcutData.h

Make shortcuts use the app icon

---

gradleriobase/build.gradle

Relies on https://github.com/wpilibsuite/GradleRIO/pull/744

Add annotations to build dependencies

---

apps/ToolsUpdater/src/main/java/Program.java

Only install .vbs on Windows

---

apps/ToolsUpdater/src/main/java/Program.java

Same issue as #431, except on Windows.

Only install python on non-windows

---

apps/ToolsUpdater/src/main/java/Program.java

Same as #433 and #434 but for C++ tools.

Only copy C++ tool .vbs files on Windows and .py files on Linux

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
scripts/versions.gradle

Fixes issues with reusing daemons

Update to Gradle 8.10.2

---

scripts/versions.gradle

Fixes case senstivity, which needed a workaround in settings.json

Update to release version of C++ plugin (1.22.9)

---

files/Choreo.sh

Resolves https://github.com/wpilibsuite/WPILibInstaller-Avalonia/issues/451

Fix Choreo.sh

---

scripts/choreo.gradle

Bundle Choreo AppImage

---

scripts/versions.gradle

cppTools = '1.23.2'
javaExt = '1.37.0'
javaDebug = '0.58.1'
javaDependency = '0.24.1'
pythonExt = '2024.22.0'
pylance = '2024.12.100'
black = '2024.4.0'

Update vscode extensions

---

scripts/versions.gradle

Update AdvantageScope to 4.1.0

---

WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs

Fix platform detection for multiple vscode on apple silicon

---

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs

This reverts commit bdd101a6a8cd641c3910d319c389e1042924dc5f.

Revert "Clean-up Choreo if previously installed (#485)"

---

.github/workflows/ci.yml

May improve robustness to network issues. https://github.com/gradle/actions/issues/631#issuecomment-2895199782

Bump gradle wrapper-validation to v4

---

.github/workflows/ci.yml
WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
build.gradle
gradle.properties
gradleriobase/build.gradle
scripts/maven.gradle
scripts/toolchain.gradle
scripts/versions.gradle
scripts/vscode.gradle
settings.gradle

Needs a new release of GradleRIO2027 to remove tools no longer being
built for 2027 and to fix toolchain location
Supersedes #534

Update to use 2027 GradleRIO and artifacts

---

WPILibInstaller-Avalonia/App.xaml
WPILibInstaller-Avalonia/ViewModels/DeprecatedOsPageViewModel.cs
WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs
WPILibInstaller-Avalonia/Views/DeprecatedOsPage.xaml.cs
WPILibInstaller-Avalonia/Views/MainWindow.xaml.cs
WPILibInstaller-Avalonia/WPILibInstaller-Avalonia.csproj

Update Avalonia to 11

---

.github/workflows/ci.yml

Saves 14gb, was 20gb free, now 34gb free

Free disk space on Linux CI
