WPILibInstaller-Avalonia/Models/VSCodeModel.cs, WPILibInstaller-Avalonia/ViewModels/ConfigurationPageViewModel.cs, WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs, WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs
I have no way to get file permissions from a zip file, so instead I must write to disk, and then call unzip on the zip
=> Use unzip on mac to extract vs code

build.gradle
Fixes #94 by not copying permissions for the libraries.
=> Only copy permissions for wpilibinstaller executable

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs, files/MavenMetaDataFixer.py, files/ScriptBase.py, files/ToolsUpdater.py
This lets Linux users run the scripts as "./OutlineViewer.py" instead of
just "python ./OutlineViewer.py".
=> Add shebangs to tools Python scripts

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
Depends on #108 so that message is shown instead of exception
Fixes #84
=> Add error popup when shortcut creation fails

WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs, WPILibInstaller-Avalonia/Views/VSCodePage.xaml
Based on feedback from beta forums post6711
Before clicking a button:
After clicking Install Single:
After clicking Install Offline:
=> Hide VS Code download progress bars that aren't used

WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs, WPILibInstaller-Avalonia/Views/CanceledPage.xaml, WPILibInstaller-Avalonia/Views/ConfigurationPage.xaml, WPILibInstaller-Avalonia/Views/FailedPage.xaml, WPILibInstaller-Avalonia/Views/FinalPage.xaml, WPILibInstaller-Avalonia/Views/InstallPage.xaml, WPILibInstaller-Avalonia/Views/MainWindow.xaml, WPILibInstaller-Avalonia/Views/StartPage.xaml, WPILibInstaller-Avalonia/Views/VSCodePage.xaml
Change select existing to use downloaded
Adjust window size so screen still fits
Reorder descriptions to match button order
=> Update Offline and skip descriptions for clarity

files/ScriptBaseCpp.py
"exec" is a shell built-in, which can't be used to run a command without
the shell. However, Popen() doesn't spawn processes in a shell by
default anyway, so we can just call that and let the script exit.
I also simplified the script.
=> Fix ScriptBaseCpp.py on Linux

.github/workflows/ci.yml
This works around a Gatekeeper bug in macOS Mojave (10.14) where it will
reject a signed-but-unnotarized disk image. All versions of macOS should
still be able to open an unsigned disk image.
=> Don't sign outer macOS disk image

WPILibInstaller-Avalonia/ViewModels/StartPageViewModel.cs, WPILibInstaller-Avalonia/Views/StartPage.xaml, build.gradle
This prevents a hypothetical re-packaging attack, where the notarized
installer application is packaged alongside a malicious sidecar payload
in a disk image. This also has the added benefit of preventing the user
from accidentally installing the wrong version if they have more than 1
WPILib disk image mounted.
Closes #58
=> Verify SHA256 of artifacts tgz on macOS

files/MavenMetaDataFixer.py, files/ScriptBase.py, files/ToolsUpdater.py
Using dirname() twice is an option, but prepending ".." has a more
obvious intent.
Fixes #154.
=> Fix path to installer's java executable

scripts/vscode.gradle
=> Use GitHub releases for java debug+dependency vscode extensions

WPILibInstaller-Avalonia/WPILibInstaller-Avalonia.csproj, build.gradle
.NET 6 breaks Windows 7 support.
=> Revert from .NET 6 to .NET 5

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
Closes #117 
In that issue, a slightly modified option 3 was chosen. It search for any exes running out of the JDK folder. If any are found, a popup is displayed telling the user to reboot.
Decided against killing processes, as its not reliable to do so. Also decided against detecting the jdks, as mid season updates can result in the MSVC runtimes changing without the JDK version changing. So we'd have to hash a bunch of files, and its probably not worth it.
=> Abort install if a JDK process to be installed over is running

WPILibInstaller-Avalonia/WPILibInstaller-Avalonia.csproj, build.gradle
We are no longer supporting Windows 7 starting in 2023.
This reverts commit baa169fb5733b3ad836b17b727732c4f694c54c4.
=> Re-upgrade to .NET 6

scripts/vscode.gradle
Change from downloading the intel chip build of VSCode on macOS to use the universal so rosseta is not when running WPILib VSCode.
=> Make macOS VSCode universal instead of intel build

build.gradle, scripts/jdk.gradle
Bump year to 2023, so it can be installed in parallel with 2022
=> Update desktop JDK to 17

files/ScriptBaseCpp.py
Previously when using the Gradle open tool command (`gradle glass`) it would open the directory in finder and the tool. This was because it ran `open tool.app currentdirectory` so it opened both. `--args` passes it instead so it works. Tested on latest stable version of macOS.
=> Use --args for macOS open command

build.gradle, distwrapper/gradle-wrapper.properties, scripts/gradlew.gradle, scripts/jdk.gradle, scripts/maven.gradle, scripts/toolchain.gradle, scripts/versions.gradle, scripts/vscode.gradle
Currently, many things have version updates where we have to update in multiple places. All the versions we have to update are in multiple places as well. This change makes it so all changes are in a single versions.gradle file, and versions are parsed where they need to be so they only have to be written once.
=> Clean up file and version reads during build

WPILibInstaller-Avalonia/Utils/ArchiveUtils.cs, WPILibInstaller-Avalonia/Utils/IArchiveExtractor.cs, WPILibInstaller-Avalonia/Utils/TarArchiveExtractor.cs, WPILibInstaller-Avalonia/Utils/ZipArchiveExtractor.cs
Closes #302 
Hopefully we never get an uncompressed size of > 4gb, or we'll have to switch to a new archiving format.
=> Fix progress bar always 0 for main extraction

WPILibInstaller-Avalonia/Utils/PlatformUtils.cs
This change allows the installer to run successfully on Windows 11 on ARM by treating it as x64 Windows.
With the advent of x64 emulation on ARM64 (introduced in Windows 11), x64 usermode applications like Visual Studio Code
run unmodified on ARM64 Windows. This includes the entire IDE stack.
Without this change the installer fails with:
```
System.Collections.Generic.KeyNotFoundException: The given key 'Invalid' was not present in the dictionary.
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at WPILibInstaller.ViewModels.VSCodePageViewModel.DownloadSingleVSCodeFunc() in D:\a\WPILibInstaller-Avalonia\WPILibInstaller-Avalonia\WPILibInstaller-Avalonia\ViewModels\VSCodePageViewModel.cs:line 329
```
On Windows 10 on ARM it will fail with an error about the architecture not …
=> Treat ARM64 Windows like x64 Windows

WPILibInstaller-Avalonia/Models/UpgradeConfig.cs, WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs, scripts/maven.gradle, scripts/tools.gradle
Since we have all the info, its safe to do so. The python and bash scripts are not removed so users can easily run them manually if necessary
=> Run tool updater and maven fixer jars directly from the installer

WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs, scripts/vscode.gradle
Instead of combining all three platforms into one zip, download each individually. On selection, look for individual file instead of comibned zip.
The existing hash check ensures the correct one is chosen. 
Fixes #335. This allows the CSA tool to download the correct version and be used for installation.
=> Use individual VSCode Zip Files

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
showRecommendationsOnlyOnDemand is duplicative of ignoreRecommendations update.channel changed to update.mode
java.home changed to java.jdt.ls.java.home
The java.home change also requires a change if the vscode extension to read the new name
=> Update VS Code settings.json for deprecations

.github/workflows/ci.yml, WPILibInstaller-Avalonia/WPILibInstaller-Avalonia.csproj
Currently pre-release, but will be released in November and is an LTS. .net 7 support ends in May 2024. 
Update non-breaking dependencies
=> Update to .net 8

gradle.properties, scripts/toolchain.gradle, scripts/versions.gradle
Version bumps:
- vscode 1.83.0
- cpptools 1.17.5
- javaext 1.23.0
- ~javadebug 0.54.0~
- ~javadep 0.23.1~
- toolchain v2024-1
- jdk 17.0.8.1+1
- gradlewrapper 8.4
=> Update for 2024.1.1-beta-1

WPILibInstaller-Avalonia/ViewModels/StartPageViewModel.cs
.Net 8 changed the location of Environment.SpecialFolder.Personal from ~ to ~/Documents. This restores the old location
https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/8.0/getfolderpath-unix
Fixes wpilibsuite/2024Beta#3
=> Install to SpecialFolder.UserProfile instead of Personal

.github/workflows/ci.yml
Split the zip files at 1500 MB boundaries to fit within GitHub release file size 2 GB limit.
Windows Explorer (at least on Windows 11) supports unzip of split zip files.
=> Add GitHub upload with split zip files

scripts/advantagescope.gradle
This will need to be done during the actual install process.
=> Don't extract AdvantageScope Mac tgz file

scripts/versions.gradle, scripts/vscode.gradle
Extensions upgrades:
- cpptools 1.19.1
- java 1.26.2023120808
- java-debug 0.55.0
- java-dependency 0.23.2023120100
The vsix files are now downloaded from Artifactory.
=> Upgrade vscode to 1.85.0 and upgrade extensions

.github/workflows/ci.yml
These are much more difficult to use than the direct downloads and their existence is confusing to users.
This reverts commit 8debfeb2d006f19edeef46aaa6cb99cda5b6def8.
=> Remove GitHub upload with split zip files

apps/ToolsUpdater/src/main/java/Program.java, apps/ToolsUpdater/src/main/java/ToolConfig.java, files/AdvantageScope.py, files/AdvantageScope.vbs, scripts/tools.gradle
Closes https://github.com/wpilibsuite/vscode-wpilib/issues/631 and https://github.com/wpilibsuite/2024Beta/issues/13. This also makes the [docs page](https://docs.wpilib.org/en/latest/docs/software/dashboards/advantagescope.html) accurate.
AdvantageScope isn't a Java or C++ tool, but I think this is a decent solution. It's added to "tools.json" with just a name and version, then there are separate scripts for launching it that don't use the existing base scripts (this requires custom handling anyway to remove an environment variable that VSCode sets by default). The app is extracted as part of the ToolsUpdater on macOS, which preserves the notarization correctly.
=> Add AdvantageScope to tools menu

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
This restores previous behavior. It was changed by redhat-developer/vscode-java#3142 
https://www.chiefdelphi.com/t/need-some-help-with-vs-code-autocomplete-features/451055
=> Disable VS-Code completion case matching

files/AdvantageScope.vbs
AdvantageScope expects the first argument to be a log file to open, which is used when launching it from a file browser on Linux and Windows. The VSCode extension passes the tool storage folder in the workspace (which AdvantageScope doesn't use), producing an error message on Windows. This is fixed by not copying the arguments to the launch script, which is consistent with the Python version.
This is unrelated to the issue where AdvantageScope is slow to launch on Windows.
=> Disable CLI args for AdvantageScope on Windows

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
=> Enable vscode system http certificates

files/frccode, files/frccode.AppArmor, scripts/vars.gradle
Allows VS Code to run on Ubuntu 24.04 without root
Also adds an AppArmor profile that a user could install if they have root
=> Run vscode without sandbox if user namespaces disabled

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
Since the .desktop file launches a script, Ubuntu 24.04 shows the generic script icon in the doc. 
This was adapted from https://ubuntuhandbook.org/index.php/2024/04/missing-icon-dock-ubuntu-2404/ 
This doesn't override the icon when system VS Code is installed, but uses the WPILib icon when system VS Code isn't installed
=> Fix icon in dock on Ubuntu 24.04

files/AdvantageScope.py, files/advantagescope.AppArmor, scripts/vars.gradle
Related to #416.
- I switched the distribution method on Linux from AppImage to an unpacked zip (the way it already works on Windows). The next release of AdvantageScope will have assets with the new format.
- I added an AppArmor profile for AdvantageScope, though since it requires root to install I don't think it's feasible to do that automatically. At a minimum the documentation should probably be updated to describe how to install AppArmor profiles (including the VSCode and wpilibutility ones).
=> Fixes for AdvantageScope on Ubuntu

scripts/tools.gradle, scripts/vars.gradle
AppArmor files are only installed on Linux and the script files that are installed depends on the platform (fixes #415).
=> Only install files if they are used by a specific platform

WPILibInstaller-Avalonia/Interfaces/IConfigurationProvider.cs, WPILibInstaller-Avalonia/Models/ChoreoConfig.cs, WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs, WPILibInstaller-Avalonia/ViewModels/StartPageViewModel.cs, build.gradle, files/Choreo.sh, files/Choreo.vbs, gradleriobase/build.gradle, scripts/choreo.gradle, scripts/maven.gradle, scripts/tools.gradle, scripts/versions.gradle
Resolves https://github.com/wpilibsuite/WPILibInstaller-Avalonia/issues/422
=> Add Choreo

scripts/versions.gradle
This makes the macOS standalone binary name match Linux so the choreo.sh launcher works on macOS.
=> Upgrade Choreo

scripts/versions.gradle
This mainly fixes ChoreoLib linking to 2024 NI libraries.
=> Upgrade to Choreo 2025.0.0-beta-6

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
If java.configuration.runtimes doesn't exist, set JavaSE-17 to WPILib JDK
If it does exist, but JavaSE-17 isn't defined, add a JavaSE-17 entry, set to WPILib JDK
If JavaSE-17 is defined, override it to WPILib JDK
Fixes wpilibsuite/allwpilib#6837
Fixes wpilibsuite/vscode-wpilib#655
=> Define java.configuration.runtimes in settings.json

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
Fixes this error. 
The rest of them seemed to be fine, it was just this one that was messed up.
=> Make java.configuration.runtimes.default a boolean instead of a string

WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs
Currently on my Raspberry Pi I cannot use my existing VS Code archive for offline installation:
=> Select tarballs for VSCode on Linux ARM

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
closes #518 
Update `RunVsCodeExtensionsSetup` method in `InstallPageViewModel.cs` to dynamically find the .app file in the `configurationProvider.InstallDirectory`.
* Use `Directory.GetDirectories` to find the .app file in the `vscode` folder.
* Update the `codeExe` variable to use the dynamically found .app file path.
* Throw an `InvalidOperationException` if there is not exactly one .app directory in the `vscode` folder.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/wpilibsuite/WPILibInstaller-Avalonia/pull/519?shareId=67531071-7b83-4f46-9998-e4398c208bb8).
=> Fix VS Code path to handle renamed .app files on macos

WPILibInstaller-Avalonia/ViewModels/InstallPageViewModel.cs
The [desktop file entry spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/file-naming.html) states that only alpha-numeric characters, dashes, and underscores are valid in desktop file names. The WPILib installer created files with spaces and parentheses, which caused issues for me when trying to launch any apps. This PR simply replaces spaces with underscores and removes the parentheses in just the file name, the actual display name is not changed.
=> Rename linux desktop files

WPILibInstaller-Avalonia/ViewModels/DeprecatedOsPageViewModel.cs, WPILibInstaller-Avalonia/ViewModels/MainWindowViewModel.cs, WPILibInstaller-Avalonia/ViewModels/StartPageViewModel.cs, WPILibInstaller-Avalonia/Views/DeprecatedOsPage.xaml
Add a cancel button to deprecated OS window.
Windows 11 also reports as Windows 10, so it's necessary to check build numbers.
Use existing frcYear variable, which required moving the deprecated page one page later. Fixes #550
=> Show deprecated message on Windows 10
